name: Test Containers

on:
  workflow_call:
    inputs:
      push:
        description: 'Whether to push the Docker image. Default: false'
        required: false
        type: boolean
        default: false

jobs:
  # For PRs and non-tag pushes to main, build without pushing
  test:
    uses: unbounded-tech/workflows-containers/.github/workflows/publish.yaml@main
    with:
      dockerfiles: |
        [
          {"dockerfile":"test-1.Dockerfile","context":"./test","prefix":"test1-"},
          {"dockerfile":"./test/test-2.Dockerfile","postfix":"test2"}
        ]
      push: ${{ github.event.inputs.push }}

