name: On Push to Main, Version and Tag For Release
on:
  push:
    branches:
    - main

permissions:
  packages: write
  contents: write

jobs:

  build-test:
    name: Build Test
    uses: unbounded-tech/workflows-containers/.github/workflows/publish.yaml@main
    with:
      dockerfiles: |
        [
          {"dockerfile":"test-1.Dockerfile","context":"./test","prefix":"test1-"},
          {"dockerfile":"./test/test-2.Dockerfile","postfix":"test2"}
        ]
      push: false

  version-and-tag:
    needs: build-test
    name: Version and Tag
    uses: unbounded-tech/workflow-vnext-tag/.github/workflows/workflow.yaml@v1.17.4
    secrets: inherit
    with:
      useDeployKey: true
      